## DSM image version
## ref: https://hub.docker.com/r/library/mysql/tags/
##
image:
  repository: "cdsdev.cumulusrepo.com/hydra_devtest/dsm" 
  tag: "2.1.4"
replicaCount: 1


imagePullPolicy: IfNotPresent
service:
  externalPort: 11080
  internalPort: 11080
  type: NodePort

## Persist data to a persitent volume
persistence:
  enabled: true
  ## If defined, volume.beta.kubernetes.io/storage-class: <storageClass>
  ## Default: volume.alpha.kubernetes.io/storage-class: default
  ##
  # storageClass:
  accessMode: ReadWriteOnce
  size: 8Gi

## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##
resources:
  requests:
    memory: 4Gi
    cpu: 2 
ingress:
  hostname: 127.0.0.1

## Default user and password to login
setup:
  dsmAdmin: admin
  dsmAdminPwd: password
